### ISSUE TITLE
OSError with fitsmask in v8.1.0

### ISSUE THREAD

**Issue by emaderubeis** [rvweeren/lofar_facet_selfcal#118]
Hi, I'm having troubles with the version 8.1.0 of the facetselfcal script. Apparently, at the end of each self-calibration cycle, it has issues in handling the "fitsmask" file. See here below an example of the error.
<img width="1409" alt="Screenshot 2024-03-14 at 09 43 51" src="https://github.com/rvweeren/lofar_facet_selfcal/assets/119594153/f3004def-1752-416b-9e3b-826502b083a6">

I got the same error using FLoCs containers v5.0.0 and v4.5.0.

**Comment by rvweeren** [comment]
Can you do the following
1. copy facetselfcal in your working dir, where that selfcal_J17....mask.fits file is located.
2.
```
from facetselfcal import *
getlargestislandsize("selfcal_J17...blabla.mask.fits")
```
3. Do you get the same error? Can you open  selfcal_J17...blabla.mask.fits with ds9 (to check it is not corrupted)

**Comment by rvweeren** [comment]
Thanks that was helpful, so the bug is not in the getlargestislandsize() function. I think I now spotted the bug, with update_fitsmask() returning a wrong variable.

Can you try to change the line below in the facetselfcal.py you are using? And then rerun and report if that solves the crash? (if you can confirm that this solves the bug I'll push the fix to the GitHub version)

Change:
` return fitsmask_list, imagename, fitsmask_list`
to
` return fitsmask, imagename, fitsmask_list`

**Comment by emaderubeis** [comment]
I made the suggested change and now everything seems to work fine!

**Comment by rvweeren** [comment]
Great, should be fixed now with the latest pull request.
