### ISSUE TITLE
extraction with DD

### ISSUE THREAD

**Issue by AnnalisaB** [rvweeren/lofar_facet_selfcal#132]
Hi, I was trying to extract a field after DD calibration, but it get stuck at the predict steps because it cannot find the box-XXX_model-pb.fits. Indeed, I notice these files are not created, while the XXX-model-pb.fits are present. I'm not sure I'm doing something wrong though, here is the command I am launching

facetselfcal.py --helperscriptspath /lofar_facet_selfcal/ --helperscriptspathh5merge /lofar_helpers/ -i A2034_UHFa_corr-avg_selfcalDD --forwidefield --noarchive --uvminim=10  --solint-list=“[‘2min’,‘5min’]” --soltype-list=“[‘scalarphase’,‘scalarcomplexgain’]” --nchan-list=[1,1] --soltypecycles-list=[0,2] --smoothnessconstraint-list=[100.,100.] --imsize=5200 --pixelsize=3.0 --beamcor=no  --channelsout=20 --niter=50000 --paralleldeconvolution=1024 --start=3 --stop=4 --multiscale --doflagging=True --useaoflagger --aoflagger-strategy=default_StokesV.lua --clipsolutions --multiscale-start=0 --parallelgridding=4 --DDE --DDE-predict=WSCLEAN --remove-outside-center --remove-outside-center-box A2034_center_ds9.reg --facetdirection=directions.txt --skipbackup 1640751677-A2034-corr_avg_compressed.MS.copy

Thanks in advance
Annalisa

**Comment by rvweeren** [comment]
Thanks for reporting, I think it is a bookkeeping bug in the code. I only recently added this option that `--remove-outside-center --remove-outside-center-box` can be used with `--DDE` and I have not tested all possible permutations.

I fixed some issues related to  `--remove-outside-center` in commit 19389e3? (on April 29 this year). You are using the facetselfcal version from April 29 or later? 

btw not that it will change your results but `--doflagging=True --clipsolutions` can be removed from the command, they are turned off in the code when you have --DDE.

**Comment by AnnalisaB** [comment]
I'm using version 9.0, I downloaded it last week from the master
Thanks also for the other comments, I left there in from a previous DI run and didn't bother removing them :-)

**Comment by rvweeren** [comment]
Small update: There is indeed a bug (when using `--DDE --remove-outside-center`), it is taking data from the wrong column. It's not the issue you reported, but you were also affected by this (hidden) one. I'm now testing a fix (for the hidden bug) and trying to reproduce your crash.

**Comment by rvweeren** [comment]
I cannot reproduce the issue you encountered (but I did fix the other bug I found) and it works fine for me. When you do a 

`ls  A2034_UHFa_corr-avg_selfcalDD_004-*` do you have all the corresponding 40 model images (0000-0019-model-[pb].fits)  ?

If they are there, could you run again with the latest version? In that case keep an eye out what it prints on the terminal (I updated the print command), just before the predict itself, coming from this line in the code

`print (squarebox, model, 'box_' + model) ` (this loops over all model images so you should see it printed 40 times because you have channelsout 20 and there are pb and non-pb model images)

the issue you reported suggests to me something is going wrong somewhere near this part.

So you expect here to see you region file, your model images, and the model image with "box_" in front. If it crashes again send me the output terminal text (ideally as far back as possible before the crash).

**Comment by AnnalisaB** [comment]
Yes,  have the model images with and without the -pb in front of .fits
Did you fix the master or some other branch?
I will run it again and let you know

**Comment by rvweeren** [comment]
>Did you fix the master or some other branch?

The master one.

**Comment by AnnalisaB** [comment]
Hi again,

I get the same error. It prints  the model and the box_model files, but not the -pb ones. Sending the log from the end of the last wsclean run.
Thanks in advance

[log_DDextract.txt](https://github.com/rvweeren/lofar_facet_selfcal/files/15431076/log_DDextract.txt)

**Comment by rvweeren** [comment]
Thanks this is helpful info, it suggests to me that the "model pb" images are not there OR they are missed by the glob statement because their filenames do not match what I expected.

what does: 
```
import glob
imageout = "A2034_UHFa_corr-avg_selfcalDD_004"
modellist = sorted(glob.glob(imageout + '-????-*model*.fits'))
print(modellist)
```
Are the model pb images in the list? 

You mentioned before the model pb images were there so I'm confused why the above glob statement would miss them. If they are present, can you indicate their precise filenames? (so the names of these model pb channel images)

**Comment by rvweeren** [comment]
Additional question: Can you show me the last part of the fitsheader (so the WSClean command used) for A2034_UHFa_corr-avg_selfcalDD_004-MFS-image.fits? I sort of have an idea what's going wrong (it would be triggered by using MeerKAT data as the primary beam treatment is different from LOFAR, which was the case I tested myself)

(`fitsheader A2034_UHFa_corr-avg_selfcalDD_004-MFS-image.fits`)

**Comment by AnnalisaB** [comment]
Ok, so:
I have the A2034_UHFa_corr-avg_selfcalDD_**003**-*-model-pb but not the A2034_UHFa_corr-avg_selfcalDD_**004**-*-model-pb files

I'm putting start=3 stop=4 now, I thought it would search for the  model of the  3rd selfcal loop this way, maybe I'm wrong.

**Comment by AnnalisaB** [comment]
About the last wsclean command used in the header, here it goes:
HISTORY wsclean -no-update-model-required -minuv-l 10.0 -size 5200 5200 -reorder
HISTORY  -weight briggs -0.5 -parallel-reordering 4 -mgain 0.8 -data-column DATA
HISTORY  -join-channels -channels-out 20 -parallel-deconvolution 1024 -parallel-
HISTORY gridding 4 -auto-mask 2.5 -auto-threshold 0.5 -multiscale -multiscale-sc
HISTORY ale-bias 0.75 -multiscale-max-scales 9 -fits-mask A2034_UHFa_corr-avg_se
HISTORY lfcalDD_003-MFS-image.fits.mask.fits -save-source-list -fit-spectral-pol
HISTORY  3 -pol i -baseline-averaging 1.887976354320789 -gridder wgridder -wgrid
HISTORY der-accuracy 0.0001 -name A2034_UHFa_corr-avg_selfcalDD_004 -scale 3.0ar
HISTORY csec -nmiter 12 -niter 50000 1640751677-A2034-corr_avg_compressed.MS.cop
HISTORY y

**Comment by AnnalisaB** [comment]
Thanks again for checking

**Comment by rvweeren** [comment]
I see what's going wrong now, the WSCLean command to make  A2034_UHFa_corr-avg_selfcalDD_004 is incorrect. Since you have MeerKAT data it then does not produce the pb images (and it also explains why my own test did not reproduce the issue as I was testing it on LOFAR data).

>I'm putting start=3 stop=4 now, I thought it would search for the model of the 3rd selfcal loop this way, maybe I'm wrong.

The last selfcal image is 003 indeed, however, for the "box extract" it makes one extra image, so that's why you get 004 (the reason being that then the image matches the last calibration table). Now for that one extra imaging command that makes 004 my the code use the wrong WSCLean call. I should use the same command as for 003. I will work on a fix.

**Comment by rvweeren** [comment]
Update: the bug should be fixed now in the latest master branch.

**Comment by AnnalisaB** [comment]
Thanks, will try asap

**Comment by AnnalisaB** [comment]
I confirm the issue is fixed. Thanks Reinout, I'm closing it
