### ISSUE TITLE
[Question] More than on field

### ISSUE THREAD

**Issue by AlexKurek** [rvweeren/lofar_facet_selfcal#64]
I have a question - what should we do if there are more than one fields? For example, for 4C29.30, the extraction pipeline downloads 3 fields. Using DDF pipeline I was doing:
```
extraction.py 4C29.30
runwsclean.py -b 4C29.30.ds9.reg -i 4C29.30 *.dysco.sub.shift.avg.weights.ms.archive?
```
`runwsclean.py` was doing "standard" selfcal.
How should it be with facet_selfcal? Should I do `extraction.py` and then put the extracted MSs form all fields in one folder and then run `facetselfcal.py` on it?

**Comment by rvweeren** [comment]
Yes, you just give it all the ms. facetselfcal.py is just the improved version of runwsclean.py. For example:

`facetselfcal.py --auto -b mytargetbox.ds9.reg -i myimagename myms1.ms myms2.ms mymsN.ms`

 I simply changed the name because the "runwsclean" was misleading....it does more than running wsclean.
