### ISSUE TITLE
find_solint.py missing

### ISSUE THREAD

**Issue by lonbar** [rvweeren/lofar_facet_selfcal#74]
`facetselfcal.py` attempts to copy some files from a local copy of the repository to the working directory as part of its run:
```
6746    os.system('cp ' + args['helperscriptspath'] + '/plot_tecandphase.py .')
6747    os.system('cp ' + args['helperscriptspath'] + '/lin2circ.py .')
6748    os.system('cp ' + args['helperscriptspath'] + '/BLsmooth.py .')
6749    os.system('cp ' + args['helperscriptspath'] + '/polconv.py .')
6750    os.system('cp ' + args['helperscriptspath'] + '/vlass_search.py .')
6751    os.system('cp ' + args['helperscriptspath'] + '/VLASS_dyn_summary.php .')
6752    os.system('cp ' + args['helperscriptspath'] + '/find_solint.py .')
```
This last file is missing from the repository. This will cause the pipeline to crash when it is run with the `--compute_phasediffstat` flag [here](https://github.com/rvweeren/lofar_facet_selfcal/blob/cc9636cf30e7159619028a53b02641fd99c0a0b1/facetselfcal.py#L6826-L6829) (which is itself missing from the available input options). Is this old code that should be cleaned up, or am I missing some files?

**Comment by ggurkan** [comment]
I have just encountered the same issue and the line aims to copy find_solint.py should be replaced with the following:
os.system('cp ' + args['helperscriptspath'] + '/phasediff_scores/find_solint.py .')
because it is in the helpers/phasediff_scores/ subdirectory.

**Comment by rvweeren** [comment]
I did not realize that `find_solint.py` in lofar_helpers became essentially a sort of wrapper (compared to the older find_solint.py I was using). I will check with @jurjen93 what the best solution is.

**Comment by jurjen93** [comment]
The issue why people ran into the bug was because in `facet_selfcal` the script was searching for `find_solint.py` in `helperscriptspath` instead of `helperscriptspathh5merge`. I reorganized the `lofar_helpers` structure and the class that was imported in find_solint.py originates now from `lofar_helpers/source_selection/phasediff_output.py`. As the functionality from `find_solint.py` is in facetselfcal only used in one function, which comes from a functionality labeled by expert mode, I moved the copy line to within the function itself (also prevents people still running into bugs when they don't have the latest lofar_helpers version).
See commit: https://github.com/rvweeren/lofar_facet_selfcal/pull/106/commits/4f9b943193df55b9f69c50807188eabf7c42c5c9
It is part of a larger pull request, waiting for @rvweeren to accept or reject. Until then you can also use the phasediff branch from `lofar_facet_selfcal`.

**Comment by rvweeren** [comment]
should be fixed now
